// ── STATIC DATA ───────────────────────────────────────────────────────────

export const SCRIPTURES = [
  { text: "She is clothed with strength and dignity, and she laughs without fear of the future.", ref: "Proverbs 31:25" },
  { text: "For I know the plans I have for you, plans to prosper you and not to harm you, to give you hope and a future.", ref: "Jeremiah 29:11" },
  { text: "She sets about her work vigorously; her arms are strong for her tasks.", ref: "Proverbs 31:17" },
  { text: "I can do all this through him who gives me strength.", ref: "Philippians 4:13" },
  { text: "Those who hope in the Lord will renew their strength. They will soar on wings like eagles.", ref: "Isaiah 40:31" },
  { text: "She opens her mouth with wisdom, and the teaching of kindness is on her tongue.", ref: "Proverbs 31:26" },
  { text: "The Lord will fulfill his purpose for me; your steadfast love endures forever.", ref: "Psalm 138:8" },
];

export const ROMANCE_POOL = [
  { title: "Morning candle ritual", sub: "Light it before the world gets loud. Even one minute counts." },
  { title: "Your best mug, no rushing", sub: "Use the good one. Sit while you drink it. This is the ceremony." },
  { title: "Dressed to delight yourself", sub: "Something that makes you feel like the woman you are building toward." },
  { title: "Lunch on a real plate", sub: "Step away from your desk. Sit down. No scrolling. Just be." },
  { title: "An evening playlist", sub: "Play music you love during wind-down. You are the host of your own life." },
  { title: "Fresh flowers somewhere", sub: "One small bouquet changes the energy of the whole room." },
  { title: "Walk a different route", sub: "Same steps, different path. Notice something you have never seen." },
  { title: "PM skincare as ceremony", sub: "Slow music. Your best products. Make it ritual, not task." },
  { title: "One page by hand tonight", sub: "Write about what you are building. No prompts needed." },
  { title: "Call while driving", sub: "Turn drop-off into connection. Alexa, Lynn, Pam, or Nia." },
  { title: "Something small and good", sub: "Buy one thing just for you. Dark chocolate. Good bread. Fresh fruit." },
  { title: "Sunday outfit flat-lay", sub: "Plan your looks tonight. Every morning becomes an event." },
  { title: "Ten minutes just for reading", sub: "Not work. Not kids. Not news. Something you love." },
  { title: "Perfume before you leave", sub: "Spray it like you are going somewhere important. You are." },
  { title: "Candle at dinner tonight", sub: "Light it even on a Tuesday. Especially on a Tuesday." },
  { title: "Set a beautiful table", sub: "Even for takeout. Even alone. You deserve the good plates." },
  { title: "Evening stretch with soft light", sub: "Dim the lights. 10 minutes. Your body will thank you tomorrow." },
  { title: "Write a note to your future self", sub: "Three sentences. Where are you going? What do you believe?" },
];

export const MEALS = [
  { day: "Monday",    meal: "Sheet pan chicken & veggies",  sub: "Simple. Nourishing. Zero decisions." },
  { day: "Tuesday",   meal: "Taco bowls",                   sub: "Protein + grain + toppings. Done in 15 minutes." },
  { day: "Wednesday", meal: "Spaghetti",                    sub: "Comfort food that takes care of itself." },
  { day: "Thursday",  meal: "Sheet pan chicken & veggies",  sub: "Post-gym. Easy. Exactly what you need." },
  { day: "Friday",    meal: "Taco bowls",                   sub: "End the week with something you enjoy." },
  { day: "Weekend",   meal: "Your choice or meal prep",     sub: "Freedom. Or use Sunday to set up next week." },
];

export const ROLE_CFG = {
  work:     { label: "Work / GC Track",   color: "#7BA7BC" },
  mom:      { label: "Mom",               color: "#C47A7A" },
  partner:  { label: "Partner",           color: "#D4A5A5" },
  health:   { label: "Health",            color: "#8BA888" },
  selfcare: { label: "Self Care",         color: "#8B7098" },
  business: { label: "Side Business",     color: "#C4923A" },
  social:   { label: "Social",            color: "#4DB8A8" },
  house:    { label: "House Manager",     color: "#A89880" },
  finance:  { label: "Finance",           color: "#C47A7A" },
  driver:   { label: "Driver",            color: "#C4923A" },
};

export const TIER3_MINS = {
  work: 'Deep work block only',
  mom: 'Present at dinner',
  partner: 'One check-in with Stan',
  health: 'Water + vitamins + SPF',
  selfcare: 'PM skincare',
  business: 'Pause or repurpose',
  social: 'One text to a friend',
  house: '5-minute tidy',
  finance: 'Check one account',
  driver: 'Drop-off only',
};

export const WS_PATTERNS = {
  mon: ['busy','busy','busy','busy','busy','busy','busy','busy','free','busy','free','busy','romance','protected','busy'],
  tue: ['busy','busy','busy','busy','busy','busy','busy','busy','free','busy','free','busy','romance','protected','busy'],
  wed: ['busy','busy','busy','busy','busy','busy','busy','free','busy','free','busy','busy','romance','protected','busy'],
  thu: ['busy','busy','busy','busy','busy','busy','busy','busy','free','busy','busy','busy','finance','protected','busy'],
  fri: ['busy','busy','busy','busy','busy','busy','busy','busy','busy','busy','free','free','romance','protected','busy'],
  sat: ['free','free','busy','busy','busy','busy','free','busy','busy','romance','protected','busy'],
  sun: ['free','free','busy','busy','busy','busy','free','free','romance','protected','busy'],
};

export const SCHEDULE = {
  mon: [
    { time:"6:00", role:"morning", task:"The Elegance Hour begins", sub:"Light your candle. Yoga mat. This is your time before the world gets loud.", gem:"🕯 candle · 🧘 stretch" },
    { time:"6:10", role:"morning", task:"Coffee with intention", sub:"Your favorite mug. Sit while you drink it. One gratitude or one intention for today." },
    { time:"6:30", role:"selfcare", task:"Dressed with joy", sub:"Something that makes you feel good. Hair done as a choice, not a chore." },
    { time:"6:45", role:"driver", task:"School drop-off", sub:"6:45–7:15am" },
    { time:"7:15", role:"selfcare", task:"Shower & full get-ready", sub:"Good body wash. Moisturize like you love yourself. Full AM skincare." },
    { time:"8:00", role:"health", task:"Breakfast at the table", sub:"Not standing at the counter. Overnight oats, egg bites, or avocado toast." },
    { time:"8:15", role:"work", task:"Check your planner — one WIN for today", sub:"What is the one thing that would make today feel like a success?" },
    { time:"8:30", role:"work", task:"Log in like a CEO", sub:"You are already grounded and elegant. Work begins." },
    { time:"9:00", role:"finance", task:"Balance check (2 min)", sub:"Open banking apps. Check all balances. Acknowledge. Close. No shame." },
    { time:"9:05", role:"work", task:"GC-track deep work", sub:"Strategic deliverables only. Protect this block." },
    { time:"12:00", role:"health", task:"Lunch like you matter", sub:"Step away from your desk. Real food on a real plate. No scrolling." },
    { time:"1:00", role:"work", task:"Core work / meetings", sub:"Advisory, team, cross-functional. Delegate junior work." },
    { time:"3:00", role:"work", task:"Learning break (10–15 min)", sub:"Day 1: Faceless IG tutorial. Rotate daily." },
    { time:"3:15", role:"work", task:"Email check + desk check-in", sub:"How do you feel? Water, stretch, breathe. Then close loops." },
    { time:"4:00", role:"business", task:"Business block (30 min)", sub:"Instagram or product work. Stick to the plan." },
    { time:"7:00", role:"mom", task:"Easy elegant dinner", sub:"Sheet pan chicken & veggies. Real plate. Candle. Music you love.", gem:"🕯 candle at dinner" },
    { time:"7:45", role:"selfcare", task:"Your hour — do what brings you joy", sub:"Read, skincare, call a friend. No work email. No doomscrolling." },
    { time:"8:30", role:"house", task:"Prep for tomorrow (5 min)", sub:"Lay out tomorrow's clothes. Check planner. 5-minute tidy." },
    { time:"9:00", role:"selfcare", task:"Wind down — full skincare ritual", sub:"Monday = exfoliation night. Journal 1 win. Phone on Do Not Disturb.", gem:"💜 PM skincare" },
    { time:"10:00", role:"health", task:"Sleep", sub:"6:00am is coming. Rest is your strategy." },
  ],
  tue: [
    { time:"6:00", role:"morning", task:"The Elegance Hour", sub:"Candle. Stretch. Your time.", gem:"🕯 candle · 🧘 stretch" },
    { time:"6:10", role:"health", task:"Strength workout #1 (25 min)", sub:"Bodyweight/kettlebell at home. Full circuit x3. This is your legacy work." },
    { time:"6:35", role:"morning", task:"Coffee with intention", sub:"Your favorite mug. One gratitude. One intention." },
    { time:"6:45", role:"driver", task:"School drop-off", sub:"6:45–7:15am" },
    { time:"7:15", role:"selfcare", task:"Shower & full get-ready", sub:"Good body wash. Moisturize. Full AM skincare. Dressed with joy." },
    { time:"8:00", role:"health", task:"Breakfast at the table", sub:"Protein + fiber. Sit down. Tuesday = tretinoin tonight — drink extra water." },
    { time:"8:30", role:"work", task:"Log in like a CEO", sub:"You are grounded. Work begins." },
    { time:"9:00", role:"finance", task:"Balance check (2 min)", sub:"Open apps. Look. Acknowledge. Close." },
    { time:"9:05", role:"work", task:"GC-track deep work", sub:"High-value deliverables only." },
    { time:"12:00", role:"health", task:"Lunch like you matter", sub:"Away from desk. Real plate. No scrolling." },
    { time:"1:00", role:"social", task:"Nonprofit board block", sub:"Board prep, governance, stewardship." },
    { time:"3:00", role:"work", task:"Learning break (10–15 min)", sub:"Day 2: Financial literacy video." },
    { time:"3:15", role:"work", task:"Email check + stretch", sub:"How do you feel? Water. Breathe. Close loops." },
    { time:"4:00", role:"business", task:"Business block", sub:"Content creation or product development." },
    { time:"7:00", role:"mom", task:"Taco bowls", sub:"Protein + grain + toppings. Real plate. Candle. Music.", gem:"🕯 candle at dinner" },
    { time:"7:45", role:"selfcare", task:"Your hour", sub:"Whatever brings you joy. No exceptions." },
    { time:"8:30", role:"house", task:"Prep for tomorrow", sub:"Clothes laid out. Planner checked. 5-minute tidy." },
    { time:"9:00", role:"selfcare", task:"PM skincare", sub:"Tuesday = tretinoin night. Journal 1 win.", gem:"💜 PM skincare" },
    { time:"10:00", role:"health", task:"Sleep", sub:"" },
  ],
  wed: [
    { time:"6:00", role:"morning", task:"The Elegance Hour", sub:"Midweek reset. Candle. Stretch. Hold your intention.", gem:"🕯 candle · 🧘 stretch" },
    { time:"6:10", role:"morning", task:"Coffee with intention", sub:"Sit. Breathe. One thing you are grateful for today." },
    { time:"6:35", role:"selfcare", task:"Dressed with joy", sub:"Something that makes you feel good. You choose." },
    { time:"6:45", role:"driver", task:"School drop-off", sub:"6:45–7:15am" },
    { time:"7:15", role:"selfcare", task:"Shower & full get-ready", sub:"Good body wash. Full AM skincare." },
    { time:"8:00", role:"health", task:"Breakfast at the table", sub:"Protein + fiber. Sit down. Check your planner." },
    { time:"8:30", role:"work", task:"Log in like a CEO", sub:"Already grounded. Work begins." },
    { time:"9:00", role:"finance", task:"Balance check (2 min)", sub:"Open apps. Look. Acknowledge. Close." },
    { time:"9:05", role:"work", task:"GC-track deep work", sub:"Strategic deliverables. Delegate junior work." },
    { time:"12:00", role:"health", task:"Lunch + walk (combined)", sub:"Eat first. Walk after. Nourishment and steps together." },
    { time:"1:00", role:"work", task:"Health Law Association block", sub:"Programming, event moderation prep." },
    { time:"3:00", role:"work", task:"Learning break (10–15 min)", sub:"Rotate: IG tutorial or financial literacy." },
    { time:"3:15", role:"work", task:"Check-in + email", sub:"How do you feel? Water. Stretch. Close loops." },
    { time:"4:00", role:"business", task:"Business block", sub:"Systems, backend, or batch content." },
    { time:"7:00", role:"mom", task:"Spaghetti", sub:"The classic. Comfort. Real plate. Candle. Music.", gem:"🕯 candle at dinner" },
    { time:"7:45", role:"partner", task:"Your hour + partner time", sub:"Intentional time with Stan. Or your joy hour. Your call." },
    { time:"8:30", role:"house", task:"Prep for tomorrow", sub:"Clothes out. Planner. 5-minute tidy." },
    { time:"9:00", role:"selfcare", task:"PM skincare", sub:"Wednesday = exfoliation night. Journal 1 win.", gem:"💜 PM skincare" },
    { time:"10:00", role:"health", task:"Sleep", sub:"" },
  ],
  thu: [
    { time:"6:00", role:"morning", task:"The Elegance Hour", sub:"Candle. Stretch. Gym tonight — let that energy build.", gem:"🕯 candle · 🧘 stretch" },
    { time:"6:10", role:"morning", task:"Coffee with intention", sub:"Your favorite mug. One intention. You are ready." },
    { time:"6:35", role:"selfcare", task:"Dressed for the day", sub:"Layer for gym tonight. Practical and still you." },
    { time:"6:45", role:"driver", task:"School drop-off", sub:"6:45–7:15am" },
    { time:"7:15", role:"selfcare", task:"Shower & AM skincare", sub:"Full get-ready. Thursday = tretinoin tonight — hydrate all day." },
    { time:"8:00", role:"health", task:"Breakfast at the table", sub:"Protein + fiber. Fuel for work and for the gym." },
    { time:"8:30", role:"work", task:"Log in like a CEO", sub:"Grounded. Elegant. Ready." },
    { time:"9:00", role:"finance", task:"Balance check (2 min)", sub:"Open apps. Look. Acknowledge. Close." },
    { time:"9:05", role:"work", task:"GC-track deep work", sub:"High-stakes deliverables. Protect this block." },
    { time:"12:00", role:"health", task:"Lunch like you matter", sub:"Real food. Real plate. Away from desk." },
    { time:"1:00", role:"work", task:"Team development + CLM work", sub:"Develop reports. Delegate clearly." },
    { time:"3:00", role:"work", task:"Learning break (10–15 min)", sub:"Financial literacy video or IG tutorial." },
    { time:"3:15", role:"work", task:"Check-in + email wrap", sub:"How do you feel? Water. Prep for gym. Close loops." },
    { time:"5:30", role:"health", task:"Gym — strength workout #2", sub:"45 min full circuit. Bone density. This is your legacy.", gem:"💪 strength" },
    { time:"7:00", role:"mom", task:"Sheet pan chicken & veggies", sub:"Post-gym. Easy. Nourishing. Real plate. Candle.", gem:"🕯 candle at dinner" },
    { time:"7:45", role:"finance", task:"Weekly finance check-in", sub:"15–20 min. Balances, bills, one financial win noted." },
    { time:"8:30", role:"house", task:"Prep for tomorrow", sub:"Friday outfit laid out. Planner. 5-minute tidy." },
    { time:"9:00", role:"selfcare", task:"PM skincare", sub:"Thursday = tretinoin night. Journal 1 win.", gem:"💜 PM skincare" },
    { time:"10:00", role:"health", task:"Sleep", sub:"Tomorrow is your deep work day. Rest well." },
  ],
  fri: [
    { time:"6:00", role:"morning", task:"The Elegance Hour — finish strong", sub:"Candle. Stretch. You made it through another full week.", gem:"🕯 candle · 🧘 stretch" },
    { time:"6:10", role:"morning", task:"Coffee with intention", sub:"Friday coffee hits different. What are you proud of this week?" },
    { time:"6:35", role:"selfcare", task:"Dressed with intention", sub:"Friday presence. You have earned this." },
    { time:"6:45", role:"driver", task:"School drop-off", sub:"6:45–7:15am" },
    { time:"7:15", role:"selfcare", task:"Shower & full get-ready", sub:"Friday = exfoliation tonight. Start the day hydrated." },
    { time:"8:00", role:"health", task:"Breakfast at the table", sub:"Something you love. Treat yourself slightly." },
    { time:"8:30", role:"work", task:"Log in like a CEO — deep work day", sub:"Friday is protected. No new meetings. GC-track thinking time." },
    { time:"9:00", role:"finance", task:"Balance check (2 min)", sub:"Open apps. Look. Acknowledge. Close." },
    { time:"9:05", role:"work", task:"Deep work (protected)", sub:"The best strategic thinking you do all week." },
    { time:"11:00", role:"work", task:"Week close + GC reflection", sub:"Where did you show up as a GC this week?" },
    { time:"12:00", role:"health", task:"Lunch — treat yourself", sub:"Something you enjoy. You worked hard." },
    { time:"1:00", role:"work", task:"Admin + filings wrap-up", sub:"Close loops. No new projects after 2pm." },
    { time:"3:00", role:"work", task:"Learning break", sub:"Your choice. Something that feeds your mind." },
    { time:"3:15", role:"white", task:"White space — do not fill this", sub:"Buffer. Flex. Breathe. Let Friday land." },
    { time:"4:30", role:"house", task:"Weekend prep", sub:"Saturday plan confirmed. Meal status checked." },
    { time:"7:00", role:"partner", task:"Your choice or taco bowls", sub:"Stan + family. Decompress. Candle. Music.", gem:"🕯 candle at dinner" },
    { time:"7:45", role:"selfcare", task:"Your hour — no exceptions", sub:"Whatever restores you. You have earned it." },
    { time:"8:30", role:"house", task:"Light prep for weekend", sub:"Loose ends. Nothing heavy." },
    { time:"9:00", role:"selfcare", task:"PM skincare", sub:"Friday = exfoliation night. Journal 1 win. Phone off.", gem:"💜 PM skincare" },
    { time:"10:00", role:"health", task:"Sleep", sub:"" },
  ],
  sat: [
    { time:"8:00", role:"morning", task:"Slow morning — no alarm", sub:"First 30 minutes belong to no one else. Coffee first.", gem:"🕯 candle · no rush" },
    { time:"8:30", role:"selfcare", task:"Full Tier 1 AM skincare", sub:"This is your skin investment day. All 7 steps." },
    { time:"9:00", role:"health", task:"Intentional breakfast", sub:"Something nourishing and good. Sit at the table." },
    { time:"9:30", role:"house", task:"Meal prep (1–2 hours)", sub:"Put on a playlist. Roast. Batch. Portion. Done.", gem:"🎵 good playlist" },
    { time:"10:30", role:"health", task:"Gym — strength workout #3", sub:"45 min full circuit. Bone density. Your most important health investment." },
    { time:"12:00", role:"health", task:"Lunch — something you love", sub:"No rush. Sit down. You worked." },
    { time:"1:00", role:"business", task:"Business deep work block", sub:"1–2 hrs. Instagram batch or journal product dev." },
    { time:"3:00", role:"white", task:"White space — protected", sub:"No plans. This is non-negotiable recovery time." },
    { time:"5:00", role:"mom", task:"Family / personal time", sub:"Ethan or Evan. Quality presence over quantity." },
    { time:"7:00", role:"partner", task:"Weekend dinner — your choice", sub:"Stan + family. Something good. Real plates. Candle.", gem:"🕯 candle at dinner" },
    { time:"8:30", role:"house", task:"Sunday prep start", sub:"Outfit flat-lay for the week. Water bottles. Kitchen check." },
    { time:"9:00", role:"selfcare", task:"PM skincare", sub:"Saturday = azelaic acid night." },
    { time:"10:00", role:"health", task:"Sleep", sub:"" },
  ],
  sun: [
    { time:"8:00", role:"morning", task:"Slow wake — spiritual anchor", sub:"Proverbs 31:25. No rushing. This day belongs to you first.", gem:"🕯 candle · Proverbs 31:25" },
    { time:"8:30", role:"selfcare", task:"Full Tier 1 AM skincare", sub:"Sunday = best skin day. All 7 steps." },
    { time:"9:00", role:"health", task:"Intentional breakfast", sub:"Something warm and nourishing. Protein + fiber. Table, not counter." },
    { time:"9:30", role:"house", task:"Sunday reset ritual (20 min)", sub:"Calendar review. Outfit prep. Water bottles filled. Quick tidy." },
    { time:"10:00", role:"house", task:"Meal prep if not done Saturday", sub:"Anchor proteins. Overnight oats x5. Batch grains. Soul seasoning." },
    { time:"12:00", role:"ritual", task:"Weekly setup — Claude ritual", sub:"Run your weekly setup. Tier, intention, Big 3. Set the whole week." },
    { time:"1:30", role:"white", task:"White space / rest", sub:"Flex. Rest if you need it. This time is protected." },
    { time:"3:00", role:"mom", task:"Family time", sub:"Ethan / Evan / Stan. Quality presence." },
    { time:"5:00", role:"social", task:"Social check-in", sub:"Text Alexa, Lynn, Pam, or Nia. One is enough." },
    { time:"7:00", role:"partner", task:"Family dinner — your choice", sub:"Stan + family. Last easy evening.", gem:"🕯 candle at dinner" },
    { time:"8:30", role:"house", task:"Wind-down prep", sub:"Monday outfit confirmed. Water bottle ready. Planner set." },
    { time:"9:00", role:"selfcare", task:"PM skincare", sub:"Sunday = tretinoin night. Journal 1 win tonight." },
    { time:"10:00", role:"health", task:"Sleep", sub:"You are ready. Rest." },
  ],
};

export const RITUALS = [
  {
    id: "morning", icon: "☀️", label: "Morning check-in", desc: "Scripture, affirmation, today's one win",
    prompt: (d) => `You are Angela's life operating system. Run her daily morning check-in.\n\nAngela is a 53-year-old Black woman, senior in-house counsel on GC track. She has ADHD and values elegance, joy, and simplicity. Her north star: "I will not spend my life reacting. I will spend it leading — myself first." Today's tier: Tier ${d.tier||2}. Context: ${d.weekNote||'standard day'}.\n\n1. Open with a grounding scripture or affirmation for a Black woman building legacy at 53.\n2. Name her ONE win to focus on today — simple, clear, achievable.\n3. Her top 3 priorities for today, tier-matched and specific.\n4. One transformation touchpoint — something small she can do for herself today.\n5. Close with: "You have everything you need. Go lead." (warmer if she signals struggle)\n\nBe warm, direct, brief. She has ADHD — no long lists. Three things maximum per section.`
  },
  {
    id: "weekly", icon: "📋", label: "Weekly setup", desc: "Sunday planning — tier, intention, role goals",
    prompt: (d) => `You are running Angela's Sunday Weekly Planning Session.\n\nAngela: 53-year-old Black woman, senior in-house counsel on GC track. ADHD. Values elegance, joy, simplicity. 10 life roles. Tier ${d.tier||2} week. Constraints: ${d.constraints||'none'}. Context: ${d.weekNote||''}.\n\nGenerate her weekly plan — simple and clear:\n1. WEEKLY INTENTION — one elegant sentence\n2. WEEKLY BIG 3 — the only 3 things that truly matter this week\n3. ROLE SNAPSHOT — for each of her 10 roles, one sentence only\n4. PROTECTION LIST — 3 non-negotiables no matter what\n5. ENERGY NOTE — one piece of specific guidance\n6. Close: "What would make this week feel like a win?"\n\nADHD note: be specific, not exhaustive. Short sentences. Clear actions. No overwhelm.`
  },
  {
    id: "evening", icon: "🌙", label: "Evening recap", desc: "Daily wins + tomorrow's one thing",
    prompt: (d) => `You are running Angela's Evening Recap ritual.\n\nAngela's tier today: Tier ${d.tier||2}. Context: ${d.weekNote||'end of day'}.\n\n1. Ask: what was your one win today?\n2. What carries forward to tomorrow?\n3. Quick check: water, movement, skincare — one honest sentence.\n4. Tomorrow's ONE anchor — the single most important thing.\n5. Tomorrow's skincare reminder based on day of week.\n6. Close warmly. She is winding down.\n\nBe brief. She needs rest, not a debrief.`
  },
  {
    id: "weekclose", icon: "🪞", label: "Week close", desc: "Friday reflection — wins, GC pulse",
    prompt: (d) => `You are running Angela's Friday Week Close.\n\nAngela: senior in-house counsel on GC track. Tier ${d.tier||2} this week. Context: ${d.weekNote||''}.\n\n1. Ask: how did the week go in one word?\n2. WINS — name 3 wins across different domains\n3. CARRYOVERS — what moves forward vs what gets released?\n4. GC PULSE — one moment she showed up as a GC. One moment she stayed in lawyer mode.\n5. DEFAULT AUDIT — one place to train people or systems to stop defaulting to her.\n6. 5-OUT-OF-7 — celebrate yes, no spiral on no.\n7. Close: "What do you want to feel at the end of next week?"\n\nWarm. Honest. No judgment.`
  },
  {
    id: "gcprep", icon: "⚖️", label: "GC prep", desc: "Before high-visibility moments",
    prompt: (d) => `You are running Angela's GC Readiness Prep.\n\nSituation: ${d.weekNote||'high-visibility meeting or interaction'}.\n\n1. STRATEGIC FRAMING — what is really at stake for her GC trajectory?\n2. THREE POWER MOVES — specific things that signal GC-level thinking\n3. TWO QUESTIONS TO ASK — enterprise-level thinking\n4. PRESENCE NOTE — one sentence on how to carry herself\n5. ANCHOR THOUGHT — one sentence she holds as she walks in\n\nTreat her like the GC she is becoming.`
  },
  {
    id: "tiercheck", icon: "⚡", label: "Tier check", desc: "Quick capacity reset — anytime",
    prompt: (d) => `You are running Angela's Tier Check — a fast, compassionate capacity reset.\n\nContext: ${d.weekNote||'mid-week check-in'}.\n\nAsk 4 rapid questions (she answers 1–10 or one word):\n1. Energy right now?\n2. Mental clarity?\n3. Emotional weight today?\n4. Body feeling okay?\n\nThen tell her:\n- Which tier she is in RIGHT NOW\n- What that means for the rest of her day\n- One permission she has (what she can let go)\n- One anchor action\n\nFast. Grounding. Compassionate. The system is designed for this.`
  },
];
